bookmarks/account/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("users/", views.user_list, name="user_list"),
    path("users/follow/", views.user_follow, name="user_follow"),
    path("users/<username>/", views.user_detail, name="user_detail"),
]

bookmarks/bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("images/", include("images.urls", namespace="images")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = "images"


urlpatterns = [
    path("create/", views.image_create, name="create"),
    path(
        "detail/<int:id>/<slug:slug>/",
        views.image_detail,
        name="detail",
    ),
    path("like/", views.image_like, name="like"),
    path("", views.image_list, name="list"),
    path("ranking/", views.image_ranking, name="ranking"),
]

bookmarks/account/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(
        upload_to="users/%Y/%m/%d/",
        blank=True,
        default="default/default_profile.png",
    )

    def __str__(self):
        return f"Profile of {self.user.username}"


class Contact(models.Model):
    user_from = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="rel_from_set",
        on_delete=models.CASCADE,
    )
    user_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="rel_to_set",
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=["-created"]),
        ]

        ordering = ["-created"]

    def __str__(self):
        return f"{self.user_from} follows {self.user_to}"


user_model = get_user_model()
user_model.add_to_class(
    "following",
    models.ManyToManyField(
        "self", through=Contact, related_name="followers", symmetrical=False
    ),
)

bookmarks/account/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label="Repeat password",
        widget=forms.PasswordInput,
    )

    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "email"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]

    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("Email already in use.")
        return data


class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "email"]

    def clean_email(self):
        data = self.cleaned_data["email"]
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError("Email already in use.")
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["date_of_birth", "photo"]

bookmarks/account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404

from .forms import (
    LoginForm,
    UserRegistrationForm,
    UserEditForm,
    ProfileEditForm,
)
from .models import Profile, Contact
from django.views.decorators.http import require_POST
from actions.utlis import create_action
from actions.models import Action


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd["username"],
                password=cd["password"],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse("Authenticated successfully")
                else:
                    return HttpResponse("Disabled account")
            else:
                return HttpResponse("Invalid credentials")

    if request.method == "GET":
        form = LoginForm()
    return render(request, "account/login.html", {"form": form})


@login_required
def dashboard(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list(
        "id",
        flat=True,
    )
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)

    actions = actions.select_related(
        "user",
        "user__profile",
    ).prefetch_related(
        "target"
    )[:10]

    return render(
        request,
        "account/dashboard.html",
        {
            "section": "dashboard",
            "actions": actions,
        },
    )


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
        # create profile for user
        Profile.objects.create(user=new_user)
        create_action(new_user, "has created an account")
        return render(
            request,
            "account/register_done.html",
            {"new_user": new_user},
        )
    if request.method == "GET":
        user_form = UserRegistrationForm()
    return render(
        request,
        "account/register.html",
        {"user_form": user_form},
    )


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(
            instance=request.user,
            data=request.POST,
        )
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES,
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # django messages
            messages.success(request, "Profile updated successfully")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(
        request,
        "account/edit.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
        },
    )


User = get_user_model()


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(
        request,
        "account/user/list.html",
        {
            "section": "people",
            "users": users,
        },
    )


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(
        request,
        "account/user/detail.html",
        {
            "section": "people",
            "user": user,
        },
    )


@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get("id")
    action = request.POST.get("action")
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == "follow":
                Contact.objects.get_or_create(
                    user_from=request.user,
                    user_to=user,
                )
                create_action(request.user, "is following", user)
            else:
                Contact.objects.filter(
                    user_from=request.user,
                    user_to=user,
                ).delete()
            return JsonResponse({"status": "ok"})
        except User.DoesNotExist:
            return JsonResponse({"status": "error"})
    return JsonResponse({"status": "error"})

bookmarks/account/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon-book.png' %}">
    <!-- font awesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dashboard' %}">My Site</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          {% if request.user.is_authenticated %}
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <a class="nav-link {% if section == 'dashboard' %}text-primary{% endif %}" href="{% url 'dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if section == 'images' %}primary{% endif %}" href="{% url 'images:list' %}">Images</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if section == 'people' %}active{% endif %}" href="{% url 'user_list' %}">People</a>
              </li>
            </ul>
            <span class="navbar-text">
              Hello {{ request.user.first_name|default:request.user.username }}
            </span>
            <form class="d-inline ms-4" action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger btn-sm">Logout</button>
            </form>
          {% else %}
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log-in</a>
              </li>
            </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <!-- Django messages -->
    <div class="toast-container position-fixed top-0 end-0 p-3">
      {% if messages %}
        {% for message in messages %}
          <div class="toast align-items-center text-white bg-{{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
              <div class="toast-body">
                {{ message|safe }}
              </div>
              <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    

    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        var toastList = [].slice.call(document.querySelectorAll('.toast'));
        toastList.map(function(toastEl) {
          var toast = new bootstrap.Toast(toastEl);
          toast.show();
        });
      });
      
      const csrftoken = Cookies.get('csrftoken');
      document.addEventListener('DOMContentLoaded', (event) => {
        // DOM loaded
        {% block domready %}
        {% endblock %}
      })
      </script>
    </script>
    

    {% block content %}
    {% endblock %}

    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>